### ISSUE TITLE
Results on LOL dataset

### ISSUE THREAD

**Issue by yarqian** [WangLiwen1994/DLN#1]
Many thanks for your work and codes. I tested your model on LOL dataset by using the DLN_finetune_LOL.pth and got 21.946db which is the same as the result reported on your paper. But when I retrained the model, the result is only 19.45db. It seems there are some problems. So would you please give me some advise about this problem?
Many thanks.

**Comment by WangLiwen1994** [comment]
Hello. Our model was pretrained at the synthesized dataset and finetuned at the LOL dataset. Did you warm up your model before the training?

**Comment by yarqian** [comment]
Yes, I followed your instruction,
### Training
It needs to manually switch the training dataset: 
1) first, train from the synthesized dataset, 
2) then, load the pretrained model and train from the real dataset
And the result of the pre-trained model is 18.34db.

**Comment by yarqian** [comment]
And I tested your pretrained model trained at synthetic dataset and the result is 19.2db and the result of the model trained by myself is only 18.34db.
Then I loaded your pretrained model trained at synthetic dataset and finetuned at the LOL dataset. And the reuslt is 20.78db. 
It seems that there are problems on both pretrained step and finetuned step.

**Comment by WangLiwen1994** [comment]
It seems your model was not fully converged. You may need to train it longer.

**Comment by yarqian** [comment]
Thank you for your suggestion. When the number of epoch for finetuning is setting to 2000 and the pre-trained model is your 'DLN_pretrained.pth', the result is the same as that reported on the paper.  And also, the number of epoch for training on synthetic dataset is also setting to 2000, but the result is also much lower than that of your pre-trained model. So it seems that the problem is on the training on synthetic dataset.

**Comment by Zruto** [comment]
> Thank you for your suggestion. When the number of epoch for finetuning is setting to 2000 and the pre-trained model is your 'DLN_pretrained.pth', the result is the same as that reported on the paper. And also, the number of epoch for training on synthetic dataset is also setting to 2000, but the result is also much lower than that of your pre-trained model. So it seems that the problem is on the training on synthetic dataset.

I want to know what went wrong when the trainset didn't change. The author trained 100 epochs and you trained 2000 epochs.I trained 100 epochs and only got 16.12db

**Comment by yarqian** [comment]
THe model was not fully converged, so I trained the model with 2000 epoches. But I can only get the similar result with that claimed on the paper, when I used the pretrained model provided by the author. When I trained the model on synthetic dataset, I cann't get the result claimed on the paper. Actually, I don't know what is the problem.
